### ISSUE TITLE
Closing client without connecting throws exception

### ISSUE THREAD

**Issue by softwareantics** [Eastrall/LiteNetwork#58]
In my application, when I'm running more than one host and attempt to close the application I get an exception.

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot disconnect with current client state: Disconnected
  Source=LiteNetwork
  StackTrace:
   at LiteNetwork.Client.Internal.LiteClientConnector.DisconnectAsync() in LiteNetwork.Client.Internal\LiteClientConnector.cs:line 76
   at LiteNetwork.Client.LiteClient.<DisconnectAsync>d__19.MoveNext() in LiteNetwork.Client\LiteClient.cs:line 69
   at LiteNetwork.Client.Hosting.LiteClientHostedService.<StopAsync>d__3.MoveNext() in LiteNetwork.Client.Hosting\LiteClientHostedService.cs:line 24
   at Microsoft.Extensions.Hosting.Internal.Host.<ForeachService>d__18`1.MoveNext() in /_/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs:line 390
   at Microsoft.Extensions.Hosting.Internal.Host.<StopAsync>d__17.MoveNext() in /_/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs:line 313
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<WaitForShutdownAsync>d__5.MoveNext() in /_/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/HostingAbstractionsHostExtensions.cs:line 111
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext() in /_/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/HostingAbstractionsHostExtensions.cs:line 69
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext() in /_/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/HostingAbstractionsHostExtensions.cs:line 79
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host) in /_/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/HostingAbstractionsHostExtensions.cs:line 53
   at Program.Main() in C:\dev\Mantanimus\src\Client\Mantanimus.Presentation\Program.cs:line 50
```

This is likely thrown because I am using more than one hosted service. I am doing this attempting to make a game using `MonoGame` with `LiteNetwork` as the client.

After careful consideration; one of two things likely needs to change to ensure this can be resolved:

1. In the hosted service, when we are stopping the `LiteClient` we should ensure that the client is connected first.
2. Or, alternatively I think if we add support to register servers and clients to the service container _without_ creating a hosted service this might also fix the issue.

**Comment by softwareantics** [comment]
This issue as well as #57 has been fixed in a project I'm maintaining named [LiteNetwork.Extensions](https://github.com/softwareantics/LiteNetwork.Extensions).

The project solves this problem by allowing the end-user to register a client as a singleton _without_ also registering a `LiteClientHostedService`.

If the project gains more popularity I'll be happy to provide more documentation or features :)

**Comment by Eastrall** [comment]
Thanks for reporting this issue and the development of the `LiteNetwork.Extensions` library. I'm glad that you like the library.

This exception is actually "by-design":
https://github.com/Eastrall/LiteNetwork/blob/d6dbced4a0bd249b96c5a2fe19df2a55039f5f1f/src/LiteNetwork/Client/Internal/LiteClientConnector.cs#L95-L103

But perhaps, instead of throwing an exception, we could just remove this check, since what you actually want is disconnect the user. So in the end, it will be disconnected.
I believe there is a "race-condition" between the `DisconnectAsync()` and the `SocketAsyncEventArgs.Completed` event. Meaning that the `Completed` event runs **before** the `DisconnectAsync()` call.

Could you provide a minimal reproduction sample for the first scenario in order to provide a fix to this?
